import type { ConditionalEdge } from "./types.js";
import { resolveEdges, type EdgeBearingStep } from "./edge-condition.js";
import { isStructuralGateStep } from "./structural-gate.js";
import { isDeliveryReadbackStep } from "../delivery-verification-gate.js";

interface QaCapStep extends EdgeBearingStep {
  readonly name: string;
  readonly description?: string;
  readonly type?: string;
  readonly qaType?: string;
  readonly agentId?: string;
  readonly toolNames?: string[];
}

interface StepRunSnapshot {
  readonly stepId: string;
  readonly status: string;
  readonly iterationIndex: number | null;
}

export interface QaCapAcceptanceRuntimeContract {
  readonly kind: "workflow_qa_cap_acceptance";
  readonly qaStepId: string;
  readonly producerStepId: string;
  readonly currentIteration: number;
  readonly maxIterations: number;
  readonly verdictEndpoint: string;
  readonly nonblockingAcceptance: {
    readonly classification: "nonblocking";
    readonly limitationsRequired: true;
  };
}

function optedBackEdges(step: QaCapStep): ConditionalEdge[] {
  return resolveEdges(step).filter((edge) => (
    edge.isBackEdge === true
    && edge.allowCapAcceptance === true
    && typeof edge.maxIterations === "number"
    && edge.maxIterations >= 1
  ));
}

/**
 * Builds the execution-only contract for a semantic QA recheck at the producer
 * rework cap. The workflow definition supplies only the opt-in flag; verdict
 * guidance is generated by the runtime and never copied into step descriptions.
 */
export function buildQaCapAcceptanceRuntimeContract(input: {
  readonly qaStep: QaCapStep;
  readonly qaIssueId: string;
  readonly steps: readonly QaCapStep[];
  readonly stepRuns: readonly StepRunSnapshot[];
}): QaCapAcceptanceRuntimeContract | null {
  if (isStructuralGateStep(input.qaStep) || isDeliveryReadbackStep(input.qaStep)) return null;

  const runByStepId = new Map(input.stepRuns.map((run) => [run.stepId, run]));
  const candidates = input.steps.flatMap((producer) => {
    const edges = optedBackEdges(producer);
    if (!edges.some((edge) => edge.stepId === input.qaStep.id)) return [];
    const producerRun = runByStepId.get(producer.id);
    if (!producerRun || producerRun.status !== "completed") return [];
    const maxIterations = Math.max(...edges.map((edge) => edge.maxIterations!));
    const currentIteration = producerRun.iterationIndex ?? 0;
    return currentIteration >= maxIterations
      ? [{ producerStepId: producer.id, currentIteration, maxIterations }]
      : [];
  });

  // A single QA linked to multiple capped producers is ambiguous. Fail closed
  // instead of teaching the agent a contract that may accept the wrong generation.
  if (candidates.length !== 1) return null;
  const candidate = candidates[0]!;
  return {
    kind: "workflow_qa_cap_acceptance",
    qaStepId: input.qaStep.id,
    ...candidate,
    verdictEndpoint: `/api/issues/${input.qaIssueId}/workflow/verdict`,
    nonblockingAcceptance: {
      classification: "nonblocking",
      limitationsRequired: true,
    },
  };
}
